#
# Copyright (c) 2024 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
################################################################################
# Application Configuration

CONFIG_DESKTOP_ROLE_HID_PERIPHERAL=y
CONFIG_DESKTOP_PERIPHERAL_TYPE_MOUSE=y
CONFIG_DESKTOP_DEVICE_PID=0x52DE
CONFIG_DESKTOP_HID_BOOT_INTERFACE_MOUSE=y

CONFIG_DESKTOP_MOTION_SIMULATED_ENABLE=y
CONFIG_DESKTOP_MOTION_SIMULATED_EDGE_TIME=8192
CONFIG_DESKTOP_MOTION_SIMULATED_SCALE_FACTOR=5

CONFIG_CAF_BUTTONS=y
CONFIG_CAF_BUTTONS_POLARITY_INVERSED=y
CONFIG_CAF_BUTTONS_PM_KEEP_ALIVE=n

CONFIG_CAF_LEDS=y

CONFIG_DESKTOP_WATCHDOG_ENABLE=y
CONFIG_DESKTOP_FAILSAFE_ENABLE=y

CONFIG_DESKTOP_CONFIG_CHANNEL_ENABLE=y
CONFIG_DESKTOP_CONFIG_CHANNEL_DFU_ENABLE=y

CONFIG_DESKTOP_USB_ENABLE=y
# Enable the only USB stack that supports USBHS
CONFIG_DESKTOP_USB_STACK_NEXT=y

CONFIG_DESKTOP_BT=n

CONFIG_DESKTOP_DVFS=n

################################################################################
# Zephyr Configuration

CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=3584
CONFIG_ISR_STACK_SIZE=2560
CONFIG_MAIN_STACK_SIZE=2816

CONFIG_BOOT_BANNER=n
CONFIG_NCS_BOOT_BANNER=n

CONFIG_NUM_COOP_PRIORITIES=10
CONFIG_NUM_PREEMPT_PRIORITIES=11

CONFIG_HEAP_MEM_POOL_SIZE=2560
CONFIG_IDLE_STACK_SIZE=512

CONFIG_HW_STACK_PROTECTION=n
CONFIG_RESET_ON_FATAL_ERROR=n

CONFIG_SPEED_OPTIMIZATIONS=y

CONFIG_REBOOT=y

CONFIG_GPIO=y

CONFIG_LED=y
# PWM not supported on this target, using GPIO instead.
CONFIG_LED_GPIO=y

################################################################################
# Disable unused features

CONFIG_SERIAL=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n

################################################################################
# DFU configuration

CONFIG_SUIT=y
CONFIG_SUIT_DFU_CANDIDATE_PROCESSING_MINIMAL=y

CONFIG_PM=y
CONFIG_PM_S2RAM=y
CONFIG_PM_S2RAM_CUSTOM_MARKING=y
